package co.syngleton.chartomancer.core_entities;

public enum CoreDataSettingNames {
    MATCH_SCORE_SMOOTHING,
    MATCH_SCORE_THRESHOLD,
    PRICE_VARIATION_THRESHOLD,
    EXTRAPOLATE_PRICE_VARIATION,
    EXTRAPOLATE_MATCH_SCORE,
    PATTERN_AUTOCONFIG,
    COMPUTATION_AUTOCONFIG,
    COMPUTATION_TYPE,
    COMPUTATION_PATTERN_TYPE,
    ATOMIC_PARTITION,
    SCOPE,
    FULL_SCOPE,
    PATTERN_LENGTH,
    PATTERN_GRANULARITY,
    COMPUTATION_DATE
}
